# csl_mapper.py

"""
Maps a single CSL-JSON record to Zotero-compatible JSON format.

Assumes:
- Valid CSL input (e.g., generated by an LLM or exported from a processor)
- Standard field names like 'type', 'author', 'title', 'issued', etc.
- This version does NOT handle extra or invalid fields — that comes in phase 2.

See: zotero_writer.py for the upload logic
"""
import json
from zotero_allowed_fields import ZOTERO_ALLOWED_FIELDS
from csl_field_mappers import (
    map_container_title,
    map_publisher_field,
    map_genre,
    map_event,
    map_title_short,
    map_note,
    map_issued_date,
    map_case_fields,
    map_bill_fields,
    map_statute_fields,
    map_hearing_fields,
    map_presentation_fields,
    map_interview_fields,
    map_audio_fields,
    map_video_fields,
    map_doi,
    map_url,
    map_pages,
    map_language,
    map_abstract,
    map_access_date,
    map_tags,
    map_extra_fields
)

# Complete mapping
CSL_TO_ZOTERO_TYPE = {
    "article": "journalArticle",
    "article-journal": "journalArticle",
    "article-magazine": "magazineArticle",
    "article-newspaper": "newspaperArticle",
    "bill": "bill",
    "book": "book",
    "broadcast": "tvBroadcast",
    "chapter": "bookSection",
    "classic": "book",  # fallback
    "dataset": "dataset",
    "entry": "encyclopediaArticle",  # ambiguous: could also be dictionary
    "entry-dictionary": "dictionaryEntry",
    "entry-encyclopedia": "encyclopediaArticle",
    "figure": "artwork",
    "graphic": "artwork",
    "interview": "interview",
    "legal_case": "case",
    "legislation": "statute",
    "manuscript": "manuscript",
    "map": "map",
    "motion_picture": "film",
    "musical_score": "audioRecording",  # no perfect match; could be document too
    "pamphlet": "book",  # fallback
    "paper-conference": "conferencePaper",
    "patent": "patent",
    "personal_communication": "email",
    "post": "forumPost",
    "post-weblog": "blogPost",
    "report": "report",
    "review": "journalArticle",
    "review-book": "journalArticle",
    "song": "audioRecording",
    "speech": "presentation",
    "thesis": "thesis",
    "treaty": "document",  # fallback
    "webpage": "webpage"
}

def map_creators(csl_item):
    """
    Convert CSL 'author' and 'editor' fields into Zotero-style 'creators' array.
    """
    creators = []

    for role in ["author", "editor"]:
        if role in csl_item:
            for person in csl_item[role]:
                if isinstance(person, dict):
                    creators.append({
                        "creatorType": role,
                        "firstName": person.get("given", ""),
                        "lastName": person.get("family", "")
                    })
                elif isinstance(person, str):
                    creators.append({
                        "creatorType": role,
                        "name": person  # Fallback to single-name
                    })

    return creators


def csl_to_zotero(csl_item):
    """
    Convert a CSL JSON item into a minimal Zotero JSON record.

    Ignores fields not in Zotero's schema for now.
    """
    csl_type = csl_item.get("type", "").lower()

    # debug
    print(f"[DEBUG] Raw CSL type: {csl_item.get('type')} → Normalised: {csl_type}")

    item_type = CSL_TO_ZOTERO_TYPE.get(csl_type, "document")

    # Use allowed field whitelist
    allowed_fields = ZOTERO_ALLOWED_FIELDS.get(item_type, [])

    # Start with required fields
    zotero_item = {
        "itemType": item_type,
        "title": csl_item.get("title", ""),
        "date": csl_item.get("issued", {}).get("raw", csl_item.get("issued", {}).get("date-parts", [[None]])[0][0]),
        "creators": map_creators(csl_item)
    }

    map_container_title(csl_item, zotero_item, item_type)
    map_publisher_field(csl_item, zotero_item, item_type)
    map_genre(csl_item, zotero_item, item_type)
    map_event(csl_item, zotero_item, item_type)
    map_title_short(csl_item, zotero_item, item_type)
    map_note(csl_item, zotero_item, item_type)
    map_issued_date(csl_item, zotero_item, item_type)
    
    map_case_fields(csl_item, zotero_item, item_type)
    map_bill_fields(csl_item, zotero_item, item_type)
    map_statute_fields(csl_item, zotero_item, item_type)
    map_hearing_fields(csl_item, zotero_item, item_type)
    map_presentation_fields(csl_item, zotero_item, item_type)
    map_interview_fields(csl_item, zotero_item, item_type)
    map_audio_fields(csl_item, zotero_item, item_type)
    map_video_fields(csl_item, zotero_item, item_type)

    map_doi(csl_item, zotero_item, item_type)
    map_url(csl_item, zotero_item, item_type)
    map_pages(csl_item, zotero_item, item_type)
    map_language(csl_item, zotero_item, item_type)
    map_abstract(csl_item, zotero_item, item_type)
    map_access_date(csl_item, zotero_item, item_type)
    map_tags(csl_item, zotero_item, item_type)
    map_extra_fields(csl_item, zotero_item, item_type)


# debug
    print("[DEBUG] Zotero item before upload:\n", json.dumps(zotero_item, indent=2))

    return zotero_item
